### ISSUE TITLE
Program doesn't download

### ISSUE THREAD

**Issue by stschubert** [matthewgadd/RobotCarDataset-Scraper#1]
Usually the program just skips everything and nothing is downloaded. Sometimes, if I'm lucky, one of many files is downloaded.
I simply call the program with python with a custom datasets.txt-file (every dataset) and file_patterns.txt (stereo_centre_01 to stereo_centre_20, gps).

Thanks for help.

**Comment by matthewgadd** [comment]
Can you attach your datasets and patterns files, and copy the command you use to call the script?

**Comment by stschubert** [comment]
This is the command, which I call from a batch-file:
`python scrape_mrgdatashare.py --downloads_dir /data/OxfordRobotCar --dataset "*" --datasets_file datasets.txt --file_pattern "*" --file_patterns_file file_patterns.txt --username user --password pw`

I have to use the quotes for the wildcards, otherwise, it fails as the wildcards are replaced with underlying files and folders.

Is there a better way to get every image-zip than simply inserting 20 lines for a specific camera?

[datasets.txt](https://github.com/matthewgadd/RobotCarDataset-Scraper/files/2971835/datasets.txt)
[file_patterns.txt](https://github.com/matthewgadd/RobotCarDataset-Scraper/files/2971836/file_patterns.txt)

**Comment by F-Barto** [comment]
Hello,
First I would like to thank you for your work on this dataset.

When just doing a git clone and running the provided command with my username and password I get the following error:

```
ScrapeMRGDatashare is starting...
got num_datasets: 1
got num_file_patterns: 1
got csrf_middleware_token: 8fAsEHXhYm3FOIS9zWZo9RnptirdfVGFfVGvpCMERgoB1CxZQTwhCAHZ9LaVBVrT
got status_code: 200
Logged in!
num_chunks_in_period: 0, period_seconds: 600
creating dataset: 2014-05-06-12-54-54
requesting file_url: http://mrgdatashare.robots.ox.ac.uk:80/download/?filename=datasets/2014-05-06-12-54-54/2014-05-06-12-54-54_vo.tar
got status_code: 200
downloading local_file_path: /mnt/c/Users/fbartocc/Downloads/2014-05-06-12-54-54/2014-05-06-12-54-54_vo.tar
Traceback (most recent call last):
  File "scrape_mrgdatashare.py", line 990, in <module>
    file_was_found = scraper.scrape(url_handler)
  File "scrape_mrgdatashare.py", line 454, in scrape
    if "File not found." in chunk:
TypeError: a bytes-like object is required, not 'str'
```

Correct me if I am wrong, but just changing ``"File not found."`` to ``b"File not found."`` would do the trick.

**Comment by matthewgadd** [comment]
Hi, see #2 for the fix

**Comment by mhheo** [comment]
Hi, Matt.
First, Thank for your efforts. :)

I got a similar problem with the other guys even if I used the latest code.
Whenever I run this code, the first two datasets in the lists are ok, but the others are not downloaded at all.

To check the reason, I modified your code slightly not to delete the tar files. 
I found that only the dummy tar files were downloaded, even the actual file exists at the homepage.

Could you check this issue? 
I used the following scripts. `datasets-long.txt` and 'file_patterns-long.txt' are the same as yours.

`
python scrape_mrgdatashare.py --downloads_dir $my_data --dataset "*" --datasets_file datasets-long.txt --file_pattern "*" --file_patterns_file file_patterns-long.txt --username $user --password $pw
`

**Comment by matthewgadd** [comment]
Hi, I have just run this again with the *long files and I am able to get past the first two datasets:

![Screen Shot 2019-03-20 at 12 03 47](https://user-images.githubusercontent.com/3154919/54683054-93065c80-4b08-11e9-920d-4153b25f579a.png)
![Screen Shot 2019-03-20 at 12 03 56](https://user-images.githubusercontent.com/3154919/54683055-94d02000-4b08-11e9-9d41-d3841502d901.png)
![Screen Shot 2019-03-20 at 12 04 45](https://user-images.githubusercontent.com/3154919/54683058-9699e380-4b08-11e9-8ae6-c5ffc3606bd7.png)
 
(third dataset downloaded fine).

Are you able to test this on a macOS machine? I just updated the README to reflect that this has been what I'm testing on, but I can test on an Ubuntu machine if you are not able to.

**Comment by mhheo** [comment]
Hi, Matt. 
As you already know, I've tested this code on Ubuntu 16.04. 
And.. unfortunately, I don't have macOS machine.

I think there is another possible reason.
Our network security manager seems to refuse when large file transfers are detected
Because when I tried to run this code on my Windows machine (the same network), the same problem occurs 

If the test on Ubuntu is ok, you probably don't need to care about this issue. 
Because it seems to be my problem :P. Sorry.

**Comment by matthewgadd** [comment]
I have added a Dockerfile (see README for quick, easy install) which starts from a fresh Ubuntu 16.04 install and checks out this code (README also shows how to mount a local directory to save the downloads to your local machine).

I have just tested this with a non-University network connection, and the script is able to get past the first two datasets.

Please let me know if you're still having problems, and we can re-open this issue.
